"""
Agent Tools Module
==================
Reusable tools that agents can use to perform specific tasks.

Each tool is a focused function that:
- Has a clear purpose
- Handles errors gracefully
- Logs its operations
- Returns structured results
"""

import json
import yaml
from typing import Dict, Any, List, Optional
from pathlib import Path
from datetime import datetime
from src.utils.logger import get_logger, log_function_call
from src.utils.validators import InputValidator, DataQualityValidator

logger = get_logger(__name__)


class SchemaDesignTool:
    """
    Tool for designing database schemas and data models.
    
    Analyzes requirements and generates optimal schema designs.
    """
    
    @staticmethod
    @log_function_call
    def design_schema(
        entities: List[str],
        relationships: List[Dict[str, str]],
        constraints: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Design a database schema based on entities and relationships.
        
        Args:
            entities: List of entity names
            relationships: List of relationship definitions
            constraints: Optional constraints (unique, not null, etc)
            
        Returns:
            Dict containing schema design
        """
        schema = {
            "version": "1.0",
            "created_at": datetime.utcnow().isoformat(),
            "tables": {}
        }
        
        # Generate table definitions
        for entity in entities:
            table_name = entity.lower().replace(' ', '_')
            schema["tables"][table_name] = {
                "columns": {
                    "id": {"type": "INTEGER", "primary_key": True, "auto_increment": True},
                    "created_at": {"type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"},
                    "updated_at": {"type": "TIMESTAMP", "nullable": True}
                },
                "indexes": ["id"],
                "constraints": constraints or []
            }
        
        # Add relationships
        schema["relationships"] = relationships
        
        logger.info("Schema designed", tables=len(schema["tables"]))
        return schema


class CodeGeneratorTool:
    """
    Tool for generating pipeline code.
    
    Creates production-ready Python code for ETL pipelines.
    """
    
    @staticmethod
    @log_function_call
    def generate_etl_code(
        source_config: Dict[str, Any],
        transformations: List[str],
        destination_config: Dict[str, Any],
        pipeline_name: str
    ) -> str:
        """
        Generate ETL pipeline code.
        
        Args:
            source_config: Source configuration
            transformations: List of transformation steps
            destination_config: Destination configuration
            pipeline_name: Name of the pipeline
            
        Returns:
            str: Generated Python code
        """
        code_template = '''"""
{pipeline_name} ETL Pipeline
Generated by DataPipelineAgent on {timestamp}

This pipeline:
- Extracts data from {source_type}
- Applies {num_transforms} transformations
- Loads data to {dest_type}
"""

import pandas as pd
from datetime import datetime
from typing import Dict, Any
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class {class_name}:
    """ETL Pipeline for {pipeline_name}"""
    
    def __init__(self):
        """Initialize pipeline configuration."""
        self.pipeline_name = "{pipeline_name}"
        self.source_config = {source_config}
        self.destination_config = {destination_config}
        
    def extract(self) -> pd.DataFrame:
        """
        Extract data from source.
        
        Returns:
            pd.DataFrame: Extracted data
        """
        logger.info(f"Extracting data from {{self.source_config['type']}}")
        
        # TODO: Implement actual extraction logic based on source type
        # This is a placeholder
        df = pd.DataFrame()
        
        logger.info(f"Extracted {{len(df)}} records")
        return df
    
    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Apply transformations to data.
        
        Args:
            df: Input dataframe
            
        Returns:
            pd.DataFrame: Transformed data
        """
        logger.info("Applying transformations")
        
        {transformation_code}
        
        logger.info("Transformations complete")
        return df
    
    def load(self, df: pd.DataFrame) -> None:
        """
        Load data to destination.
        
        Args:
            df: Data to load
        """
        logger.info(f"Loading data to {{self.destination_config['type']}}")
        
        # TODO: Implement actual load logic based on destination type
        
        logger.info(f"Loaded {{len(df)}} records")
    
    def run(self) -> Dict[str, Any]:
        """
        Execute the complete ETL pipeline.
        
        Returns:
            Dict: Pipeline execution results
        """
        start_time = datetime.now()
        logger.info(f"Starting pipeline: {{self.pipeline_name}}")
        
        try:
            # Extract
            df = self.extract()
            
            # Transform
            df = self.transform(df)
            
            # Load
            self.load(df)
            
            duration = (datetime.now() - start_time).total_seconds()
            
            result = {{
                "status": "success",
                "records_processed": len(df),
                "duration_seconds": duration,
                "timestamp": datetime.now().isoformat()
            }}
            
            logger.info(f"Pipeline completed successfully in {{duration:.2f}}s")
            return result
            
        except Exception as e:
            logger.error(f"Pipeline failed: {{str(e)}}", exc_info=True)
            return {{
                "status": "failed",
                "error": str(e),
                "timestamp": datetime.now().isoformat()
            }}


if __name__ == "__main__":
    pipeline = {class_name}()
    result = pipeline.run()
    print(json.dumps(result, indent=2))
'''
        
        # Generate transformation code
        transform_code_lines = []
        for i, transform in enumerate(transformations, 1):
            transform_code_lines.append(f"        # Step {i}: {transform}")
            transform_code_lines.append(f"        # TODO: Implement transformation logic")
            transform_code_lines.append("")
        
        transformation_code = "\n".join(transform_code_lines)
        
        # Format the template
        class_name = ''.join(word.capitalize() for word in pipeline_name.split('_')) + "Pipeline"
        
        code = code_template.format(
            pipeline_name=pipeline_name,
            timestamp=datetime.utcnow().isoformat(),
            source_type=source_config.get('type', 'unknown'),
            dest_type=destination_config.get('type', 'unknown'),
            num_transforms=len(transformations),
            class_name=class_name,
            source_config=json.dumps(source_config, indent=8),
            destination_config=json.dumps(destination_config, indent=8),
            transformation_code=transformation_code
        )
        
        logger.info("ETL code generated", lines=len(code.split('\n')))
        return code


class ValidationTool:
    """
    Tool for validating pipeline configurations and generated code.
    
    Ensures quality and safety before execution.
    """
    
    @staticmethod
    @log_function_call
    def validate_pipeline_code(code: str) -> Dict[str, Any]:
        """
        Validate generated pipeline code.
        
        Args:
            code: Python code to validate
            
        Returns:
            Dict with validation results
        """
        issues = []
        warnings = []
        
        # Check for dangerous operations
        dangerous_patterns = [
            'os.system',
            'subprocess.call',
            'eval(',
            'exec(',
            '__import__'
        ]
        
        for pattern in dangerous_patterns:
            if pattern in code:
                issues.append(f"Dangerous pattern detected: {pattern}")
        
        # Check for best practices
        if 'try:' not in code:
            warnings.append("No error handling (try/except) found")
        
        if 'logging' not in code and 'logger' not in code:
            warnings.append("No logging configured")
        
        if 'def __init__' not in code:
            warnings.append("No initialization method found")
        
        result = {
            "valid": len(issues) == 0,
            "issues": issues,
            "warnings": warnings,
            "lines_of_code": len(code.split('\n'))
        }
        
        logger.info("Code validation complete", **result)
        return result


class DocumentationTool:
    """
    Tool for generating pipeline documentation.
    
    Creates README files and data lineage diagrams.
    """
    
    @staticmethod
    @log_function_call
    def generate_documentation(
        pipeline_name: str,
        description: str,
        sources: List[Dict[str, Any]],
        transformations: List[str],
        destination: Dict[str, Any]
    ) -> str:
        """
        Generate comprehensive pipeline documentation.
        
        Args:
            pipeline_name: Pipeline name
            description: Pipeline description
            sources: Data sources
            transformations: Transform steps
            destination: Data destination
            
        Returns:
            str: Markdown documentation
        """
        doc_template = '''# {pipeline_name}

{description}

## Overview

This pipeline processes data from {num_sources} source(s) and loads it to {dest_type}.

**Generated:** {timestamp}

## Data Sources

{sources_section}

## Transformations

{transformations_section}

## Destination

**Type:** {dest_type}
**Configuration:**
```json
{dest_config}
```

## Running the Pipeline

```bash
python {pipeline_name}.py
```

## Monitoring

Check logs at: `logs/{pipeline_name}.log`

## Data Quality

- Validation: Enabled
- Profiling: Enabled
- Error handling: Configured

## Maintenance

- Owner: Data Team
- Schedule: {schedule}
- Last updated: {timestamp}
'''
        
        # Build sources section
        sources_section = []
        for i, source in enumerate(sources, 1):
            sources_section.append(f"{i}. **{source.get('name', 'Source')}**")
            sources_section.append(f"   - Type: {source.get('type', 'unknown')}")
            if 'tables' in source:
                sources_section.append(f"   - Tables: {', '.join(source['tables'])}")
        
        # Build transformations section
        transformations_section = []
        for i, transform in enumerate(transformations, 1):
            transformations_section.append(f"{i}. {transform}")
        
        doc = doc_template.format(
            pipeline_name=pipeline_name,
            description=description,
            num_sources=len(sources),
            dest_type=destination.get('type', 'unknown'),
            sources_section='\n'.join(sources_section),
            transformations_section='\n'.join(transformations_section),
            dest_config=json.dumps(destination, indent=2),
            schedule="Not specified",
            timestamp=datetime.utcnow().isoformat()
        )
        
        logger.info("Documentation generated", pipeline=pipeline_name)
        return doc